### ISSUE TITLE
add encoding to setup.py

### ISSUE THREAD

**Issue by scizen9** [phn/ref_index#1]
For this to install without errors with a modern python version all you have to do is add the encoding to the open of the README.rst:

long_description = open("README.rst", encoding="utf-8").read()

Not sure how that effects backward compatibility but maybe add a test of python version?

Thanks for the useful code.

**Comment by phn** [comment]
@scizen9 

Thank you for the feedback and sorry for the dealy. Yes, I need to make the tests more professional
 by using `pytest` and a CI such as Travis or Github Actions. Thank you for pointing this out!

I was able to successfully install this on Python 3.7 on my system and previously I have done 
this successfully on Python 2. So I am guessing this is an issue with `locale.getpreferredencoding()`
on the system you ran. Just to satisfy my curiosity can be tell me which Python version your 
were using when you tried to install this package and the output of 

```python
import locale
locale.getpreferredencoding()
```

Nevertheless I will add the change since an explicit encoding will be helpful for 
everyone.

I will release a new version after I also separate out the tests into another file and setup a CI.

Once again thank you for your feedback and sorry for the delay.

Regards,

Prasanth
